name: General Issue
description: Report a bug, request a feature, or ask a question
title: "[ISSUE]: "
labels: ["needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue!  
        Please complete the sections below so we can help you better.

  - type: dropdown
    id: type
    attributes:
      label: Type of issue
      options:
        - Bug Report
        - Feature Request
        - Question
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short summary of the issue
      placeholder: "Example: App crashes when clicking the login button"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide as much detail as possible
      placeholder: "Steps to reproduce, expected vs. actual behavior, screenshots, etc."
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: "Extra notes, links, references..."
