name: Release to Master Check

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize, reopened]

jobs:
  check-source-branch:
    if: github.base_ref == 'master' && github.head_ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Confirm release to master PR
        run: echo "This is a valid release ➜ master pull request."

  block-other-branches:
    if: github.base_ref == 'master' && github.head_ref != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: ❌ Block PRs to master from non-release branches
        run: |
          echo "Pull requests to master must come from 'release' branch."
          exit 1
